#### numpy: 다차원 연산 및 수치연산을 지원함
#### 많은 딥러닝 관련 라이브러리에서 기본 데이터 형태로 사용
#### 별칭으로 보통 np

In [15]:
import numpy as np

python_arr = [1,2,3]
np_arr1 = np.array(python_arr)
print('일반 배열', python_arr)
print('ndarray', np_arr1)

일반 배열 [1, 2, 3]
ndarray [1 2 3]


In [21]:
np_arr2 = np.array([[1,2,3], [2,3,4]])
np_arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('ndim1', type(np_arr1), np_arr1.shape, np_arr1.ndim) #dim: dimension 몇차원 배열인지 반환
print('ndim2', type(np_arr2), np_arr2.shape, np_arr2.ndim) #shape: 배열의 모양. 배열이 2개, 원소 3개
print('ndim3', type(np_arr3), np_arr3.shape, np_arr3.ndim) # 배열이 크게 2개, 그 안에 또 2개, 원소 3개

ndim1 <class 'numpy.ndarray'> (3,) 1
ndim2 <class 'numpy.ndarray'> (2, 3) 2
ndim3 <class 'numpy.ndarray'> (2, 2, 3) 3


In [49]:
print(np_arr2[0,2])    #1번째 행의 3번째 요소
print(np_arr2[:,1:3])   # 모든 행, 두번째와 세번째 열

3
[[2 3]
 [3 4]]


In [57]:
print(np_arr1 + np_arr1) # 요소별 합
print(np_arr1 * np_arr1) # 요소별 곱
print(np.sum(np_arr2))   # 합
print(np.mean(np_arr2))  # 평균
#axis 축: 0 열 방향, 1 행 방향 
#0에서 숫자가 높아질수록, 가장 큰 덩어리에서 원소까지 가는 것.
print(np_arr2)
print('열:', np_arr2.sum(axis=0))
print('행:', np_arr2.sum(axis=1))

[2 4 6]
[1 4 9]
15
2.5
[[1 2 3]
 [2 3 4]]
열: [3 5 7]
행: [6 9]


In [71]:
# 1차원 배열 생성
arr = np.arange(1,10)  # 1~9
print(arr)
# 리쉐입 3x3
print(arr.reshape(3,3))
print(arr.reshape(3,3).shape)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [73]:
# dot product ( 두 벡터의 대응하는 요소를 곱한 후 그 결과를 모두 더하는 연산)
print(np.dot(arr, arr))

285


In [77]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
# 전치 (행과 열을 서로 바꿉니다)
print(arr2.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
